---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/transfers/bulk_create":
    post:
      summary: Creates multiple credit transfers in bulk
      tags:
      - Transfers
      parameters:
      - name: Idempotency-Key
        in: headers
      responses:
        '204':
          description: Bulk transfer request created successfully
        '422':
          description: Unprocessable content
        '404':
          description: Resource not found
        '423':
          description: Resource locked
        '500':
          description: Unexpected error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transfer:
                  type: object
                  required:
                  - organization_bic
                  - organization_iban
                  - credit_transfers
                  properties:
                    organization_bic:
                      type: string
                      example: BANKBIC22
                    organization_iban:
                      type: string
                      example: DE89370400440532013000
                    credit_transfers:
                      type: array
                      items:
                        type: object
                        required:
                        - amount
                        - currency
                        - counterparty_name
                        - counterparty_bic
                        - counterparty_iban
                        - description
                        properties:
                          amount:
                            type: string
                            example: '100.00'
                          currency:
                            type: string
                            example: EUR
                          counterparty_name:
                            type: string
                            example: Alice Doe
                          counterparty_bic:
                            type: string
                            example: BICCODEXXX
                          counterparty_iban:
                            type: string
                            example: FR7630006000011234567890189
                          description:
                            type: string
                            example: Invoice payment
              required:
              - transfer
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
